### ISSUE TITLE
The "include/LineExtractor.h" was not found

### ISSUE THREAD

**Issue by wf-hahaha** [alexandervakhitov/lld-slam#2]
thanks for your work! in this code,the "include/LineExtractor.h" was not found, why?

**Comment by alexandervakhitov** [comment]
Hi! 
You do not have the LBDMOD library for line detection, or you have not set the path correctly. 

- Clone it (https://github.com/alexandervakhitov/lbdmod)

- in line 4 of the CMakeLists.txt file, please set the LBDMOD_DIR to the root of the cloned repository.
You can check that the required header is in that repository.

**Comment by wf-hahaha** [comment]
hi, thank you. If I don't use LBD or LLD (ldType: empty)
linesExtractorLeft->ExtractLines(imLeft, &mvLinesLeft, &mDescriptorsLines);
mvLinesLeft.empty = 1,  why?

**Comment by robot-mh** [comment]
> Hi!
> You do not have the LBDMOD library for line detection, or you have not set the path correctly.
> 
> * Clone it (https://github.com/alexandervakhitov/lbdmod)
> * in line 4 of the CMakeLists.txt file, please set the LBDMOD_DIR to the root of the cloned repository.
>   You can check that the required header is in that repository.

But  the root of the cloned repository have no include directory. So How to solve? give an example? I have the same problem to build.

@alexandervakhitov @wf-hahaha

**Comment by alexandervakhitov** [comment]
Please set the path to the cloned LBDMOD directory in the CMakeLists file here:
https://github.com/alexandervakhitov/lld-slam/blob/bb06981dba2eef568f464eafa3ec64430efc9b85/CMakeLists.txt#L4

**Comment by robot-mh** [comment]
yes, i just do that. for example，
cd ~/test/
git clone lbdmod.git
mkdir build
.......
sudo make install

cd lld-slam
in the CMakeLists.txt,  
set(LBDMOD_DIR "/home/xxx/test/") ,

but the "include/LineExtractor.h" was not found, why?
@alexandervakhitov
